name: tatpar_acf
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+2

environment:
  sdk: '>=3.2.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  auto_route: 7.8.4
  freezed_annotation: ^2.4.1
  hydrated_bloc: ^9.1.4
  reactive_forms: ^16.1.1
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flex_color_scheme: ^7.3.1
  reactive_image_picker: ^5.0.0
  dio: ^5.4.1
  firebase_auth: ^4.17.4
  pretty_dio_logger: ^1.3.1
  firebase_storage: ^11.6.6
  responsive_framework: ^1.4.0
  reactive_flutter_typeahead: ^2.1.0
  reactive_pin_code_fields:
  progress_builder: ^1.1.3
  djangoflow_app: ^3.7.5
  url_launcher: ^6.2.6
  flutter_debouncer: ^2.0.0
  dotted_border: ^2.1.0
  timelines: ^0.1.0
  dotted_line: ^3.2.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  intl:
  firebase_core: ^2.27.0
  djangoflow_app_links: ^2.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity: ^3.0.6
  shared_preferences: ^2.2.3
  provider: ^6.1.2

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  freezed:
  auto_route_generator: ^7.3.2
  hive_generator: ^2.0.0
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/
  - assets/json/
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
    - family: OpenSans
      fonts:
        #        - asset: assets/fonts/Open_Sans/static/OpenSans-Thin.ttf
        #          weight: 100
        #        - asset: assets/fonts/Open_Sans/static/OpenSans-ExtraLight.ttf
        #          weight: 200
        - asset: assets/fonts/Open_Sans/static/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Open_Sans/static/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Open_Sans/static/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Open_Sans/static/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Open_Sans/static/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Open_Sans/static/OpenSans-ExtraBold.ttf
          weight: 800
#        - asset: assets/fonts/Open_Sans/static/OpenSans-Black.ttf
#          weight: 900

flutter_gen:
  output: lib/configurations/constants
  integrations:
    flutter_svg: true
  fonts:
    enabled: true
    outputs:
      class_name: FontFamily

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
